# Discussion and Conclusions  
  
*Note: will add more based on discussion and additional model fitting*  
  
  - Goodness-of-fit tests indicate that none of the base models are good fits to the data. This may indicate: 
    + a lack of relationship between acuity score and probability of readmission  
    + the need to introduce covariates into the models. These covariates may be those already identified, or covariates in the dataset not yet considered, or factors not captured in the dataset  
    + Fitting null (intercept-only) models to the data in [Appendex D](#AppendixD) and [Appendix E](#AppendixE) also show issues with lack-of-fit. 
    + the need to pursue alternative methods to confirm these results. MC simulations would be my next idea.  
  - The conclusion may be that readmission rates are holding steady despite changes in acuity scores. What clinical impacts can come from this conclusion?  
  - Is there consideration in this analysis of the ANOVAs previously done to examination associations between calculated scores and demographic factors? If so, how?
